#!/usr/bin/env bash
# One-click installer for this NixOS configuration.
# Run once on a fresh NixOS installation after cloning the repo.
# Idempotent: safe to run multiple times.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colours ───────────────────────────────────────────────────────────────────
red()    { echo -e "\033[1;31m$*\033[0m"; }
green()  { echo -e "\033[1;32m$*\033[0m"; }
yellow() { echo -e "\033[1;33m$*\033[0m"; }
bold()   { echo -e "\033[1m$*\033[0m"; }

# ── Helpers ───────────────────────────────────────────────────────────────────
prompt() {
    local question="$1" default="$2" answer
    read -rp "$(bold "$question") [${default}]: " answer
    echo "${answer:-$default}"
}

confirm() {
    local answer
    read -rp "$(bold "$1") [y/N]: " answer
    [[ "${answer,,}" == "y" ]]
}

# ── Checks ────────────────────────────────────────────────────────────────────
if [[ ! -f /etc/nixos/hardware-configuration.nix ]]; then
    red "ERROR: /etc/nixos/hardware-configuration.nix not found."
    echo "Run 'nixos-generate-config' first, then re-run this script."
    exit 1
fi

# ── Gather input ──────────────────────────────────────────────────────────────
echo ""
bold "=== NixOS configuration installer ==="
echo ""

 USERNAME=$(prompt "Username" "hoshi")
 FULL_NAME=$(prompt "Full name" "$USERNAME")
 PASSWORD=$(prompt "Password" "")

 if [[ -z "$PASSWORD" ]]; then
     red "ERROR: Password cannot be empty."
     exit 1
 fi

echo ""
echo "Available hosts:"
echo "  laptop  — Honor MagicBook X16 Plus 2024 (Ryzen 7 8845HS, AMD iGPU)"
echo "  desktop — Custom desktop (Ryzen 5 7500F, NVIDIA RTX 4070 Super)"
HOSTNAME=$(prompt "Hostname" "laptop")

if [[ "$HOSTNAME" != "laptop" && "$HOSTNAME" != "desktop" ]]; then
    red "ERROR: Unknown hostname '$HOSTNAME'. Valid options: laptop, desktop."
    exit 1
fi

echo ""
echo "GPU vendor (determines which driver module is loaded):"
echo "  amd    — Laptop (Radeon iGPU)"
echo "  nvidia — Desktop (RTX 4070 Super)"
GPU=$(prompt "GPU vendor" "$([ "$HOSTNAME" = "laptop" ] && echo "amd" || echo "nvidia")")

if [[ "$GPU" != "amd" && "$GPU" != "nvidia" ]]; then
    red "ERROR: Unknown GPU vendor '$GPU'. Valid options: amd, nvidia."
    exit 1
fi

 # ── Summary ───────────────────────────────────────────────────────────────────
 echo ""
 bold "Configuration summary:"
 echo "  Username : $USERNAME"
 echo "  Full name: $FULL_NAME"
 echo "  Hostname : $HOSTNAME"
 echo "  GPU      : $GPU"
 echo "  Password : ********"
 echo ""

if ! confirm "Proceed with installation?"; then
    yellow "Aborted."
    exit 0
fi

# ── Write settings.nix ────────────────────────────────────────────────────────
cat > "$REPO_DIR/settings.nix" <<EOF
# Generated by install.sh — edit to change user-specific values.
{
  username = "$USERNAME";
  fullName = "$FULL_NAME";
}
EOF
green "✓ settings.nix written"

# ── Copy hardware configuration ───────────────────────────────────────────────
HARDWARE_DEST="$REPO_DIR/hosts/$HOSTNAME/hardware.nix"
cp /etc/nixos/hardware-configuration.nix "$HARDWARE_DEST"
green "✓ hardware.nix copied to hosts/$HOSTNAME/"

# ── Patch GPU module in host config if needed ─────────────────────────────────
# The host default.nix already references the correct GPU module by convention
# (laptop → amd, desktop → nvidia). This step is a safety check.
HOST_NIX="$REPO_DIR/hosts/$HOSTNAME/default.nix"
if ! grep -q "gpu/${GPU}.nix" "$HOST_NIX"; then
    yellow "WARNING: hosts/$HOSTNAME/default.nix does not import gpu/${GPU}.nix."
    yellow "Verify GPU module import manually before rebuilding."
fi

 # ── Build and switch ──────────────────────────────────────────────────────────
 echo ""
 bold "Running nixos-rebuild switch..."
 sudo nixos-rebuild switch --flake "$REPO_DIR#$HOSTNAME"

 # ── Set user password ──────────────────────────────────────────────────────────
 echo ""
 bold "Setting user password..."
 echo "$USERNAME:$PASSWORD" | sudo chpasswd
 green "✓ User password set"

 echo ""
 green "✓ Installation complete. Reboot recommended."
